In [ ]:
import pandas as pd
import numpy as np

In [ ]:
students = pd.DataFrame({
    "Student_Id": [101,102,102,103,104,105],
    "Name":["Rashi","Yashi","Rahul","Yashi ","Yug",None],
    "Department":["CSE","cse","cse","Data Science","DATA SCIENCE","ECE"],
    "Marks":[85,72,72,np.nan,91,67],
    "Attendance":[90,82,82,75,np.nan,88],
    "Exam_Date":["2026-09-01","01/09/2026","01/09/2026","2026-09-02","not known","2026=09-03"]
})

# **Find Missing Values**

In [ ]:
print(students.isna())
print("\nMissing count in each column:")
students.isna().sum()

   Student_Id   Name  Department  Marks  Attendance  Exam_Date
0       False  False       False  False       False      False
1       False  False       False  False       False      False
2       False  False       False  False       False      False
3       False  False       False   True       False      False
4       False  False       False  False        True      False
5       False   True       False  False       False      False

Missing count in each column:

Student_Id    0
Name          1
Department    0
Marks         1
Attendance    1
Exam_Date     0
dtype: int64

# **Remove rows containing any missing value**

In [ ]:
df_clean=students.dropna()
df_clean

   Student_Id   Name Department  Marks  Attendance   Exam_Date
0         101  Rashi        CSE   85.0        90.0  2026-09-01
1         102  Yashi        cse   72.0        82.0  01/09/2026
2         102  Rahul        cse   72.0        82.0  01/09/2026

# **Remove columns containing any missing value**

In [ ]:
df_clean=students.dropna(axis=1)
df_clean

   Student_Id    Department   Exam_Date
0         101           CSE  2026-09-01
1         102           cse  01/09/2026
2         102           cse  01/09/2026
3         103  Data Science  2026-09-02
4         104  DATA SCIENCE   not known
5         105           ECE  2026=09-03

# **Remove rows only when all values are missing**

In [ ]:
df_clean=students.dropna(how="all")
df_clean

   Student_Id    Name    Department  Marks  Attendance   Exam_Date
0         101   Rashi           CSE   85.0        90.0  2026-09-01
1         102   Yashi           cse   72.0        82.0  01/09/2026
2         102   Rahul           cse   72.0        82.0  01/09/2026
3         103  Yashi   Data Science    NaN        75.0  2026-09-02
4         104     Yug  DATA SCIENCE   91.0         NaN   not known
5         105    None           ECE   67.0        88.0  2026=09-03

# **Replace missing values using mean**

In [ ]:
clean=students.copy()
clean["Marks"]=clean["Marks"].fillna(clean["Marks"].mean())
clean["Attendance"]=clean["Attendance"].fillna(clean["Attendance"].mean())
clean["Name"]=clean["Name"].fillna("Unknown")
print(clean[["Name","Marks","Attendance"]])

      Name  Marks  Attendance
0    Rashi   85.0        90.0
1    Yashi   72.0        82.0
2    Rahul   72.0        82.0
3   Yashi    77.4        75.0
4      Yug   91.0        83.4
5  Unknown   67.0        88.0

In [ ]:
clean=students.copy()
clean["Marks"]=clean["Marks"].fillna(clean["Marks"].median())
clean["Attendance"]=clean["Attendance"].fillna(clean["Attendance"].median())
clean["Name"]=clean["Name"].fillna("Unknown")
print(clean[["Name","Marks","Attendance"]])

      Name  Marks  Attendance
0    Rashi   85.0        90.0
1    Yashi   72.0        82.0
2    Rahul   72.0        82.0
3   Yashi    72.0        75.0
4      Yug   91.0        82.0
5  Unknown   67.0        88.0

In [ ]:
df_mode=students.copy()
df_mode["Name"]=df_mode["Name"].fillna(df_mode["Name"].mode()[0])

In [ ]:
df_mode

   Student_Id    Name    Department  Marks  Attendance   Exam_Date
0         101   Rashi           CSE   85.0        90.0  2026-09-01
1         102   Yashi           cse   72.0        82.0  01/09/2026
2         102   Rahul           cse   72.0        82.0  01/09/2026
3         103  Yashi   Data Science    NaN        75.0  2026-09-02
4         104     Yug  DATA SCIENCE   91.0         NaN   not known
5         105   Rahul           ECE   67.0        88.0  2026=09-03

In [ ]:
cities=pd.Series(["Agra","Delhi","Agra",None,"Agra","Delhi","Delhi" ])
print(cities.mode())

0     Agra
1    Delhi
dtype: object

# **Handling missing values:SimpleImputer and KNNImputer**

In [ ]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
df=pd.DataFrame({
    "Age":[25,30,np.nan,22,35],
    "Salary":[50000,60000,55000,np.nan,70000]
})
print("Original Dataframe:")
print(df)

imputer=SimpleImputer(strategy="mean")
result=pd.DataFrame(imputer.fit_transform(df),columns=df.columns)
print("\nDataframe after imputation")
print(result)

Original Dataframe:
    Age   Salary
0  25.0  50000.0
1  30.0  60000.0
2   NaN  55000.0
3  22.0      NaN
4  35.0  70000.0

Dataframe after imputation
    Age   Salary
0  25.0  50000.0
1  30.0  60000.0
2  28.0  55000.0
3  22.0  58750.0
4  35.0  70000.0

In [ ]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
df=pd.DataFrame({
    "Age":[25,30,np.nan,22,35],
    "Salary":[50000,60000,55000,np.nan,70000]
})
print("Original Dataframe:")
print(df)

imputer=SimpleImputer(strategy="most_frequent")
result=pd.DataFrame(imputer.fit_transform(df),columns=df.columns)
print("\nDataframe after imputation")
print(result)

Original Dataframe:
    Age   Salary
0  25.0  50000.0
1  30.0  60000.0
2   NaN  55000.0
3  22.0      NaN
4  35.0  70000.0

Dataframe after imputation
    Age   Salary
0  25.0  50000.0
1  30.0  60000.0
2  22.0  55000.0
3  22.0  50000.0
4  35.0  70000.0

In [ ]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
df=pd.DataFrame({
    "Age":[25,30,np.nan,22,35],
    "Salary":[50000,60000,55000,np.nan,70000]
})
print("Original Dataframe:")
print(df)

imputer=SimpleImputer(strategy="constant",fill_value=0)
result=pd.DataFrame(imputer.fit_transform(df),columns=df.columns)
print("\nDataframe after imputation")
print(result)

Original Dataframe:
    Age   Salary
0  25.0  50000.0
1  30.0  60000.0
2   NaN  55000.0
3  22.0      NaN
4  35.0  70000.0

Dataframe after imputation
    Age   Salary
0  25.0  50000.0
1  30.0  60000.0
2   0.0  55000.0
3  22.0      0.0
4  35.0  70000.0

In [ ]:
import pandas as pd
import numpy as np
from sklearn.impute import KNNImputer
df=pd.DataFrame({
    "Age":[25,30,np.nan,22,35],
    "Salary":[50000,60000,55000,np.nan,70000]
})
print("Original Dataframe:")
print(df)

imputer=KNNImputer(n_neighbors=2)
result=pd.DataFrame(imputer.fit_transform(df),columns=df.columns)
print("\nDataframe after imputation")
print(result)

Original Dataframe:
    Age   Salary
0  25.0  50000.0
1  30.0  60000.0
2   NaN  55000.0
3  22.0      NaN
4  35.0  70000.0

Dataframe after imputation
    Age   Salary
0  25.0  50000.0
1  30.0  60000.0
2  27.5  55000.0
3  22.0  55000.0
4  35.0  70000.0

# **Remove exact duplicate rows**

In [ ]:
clean=students.copy()
new_data = pd.DataFrame({
    "Student_Id": [101,102,102,103,104,105],
    "Name":["Rashi","Yashi","Rahul","Yashi ","Yug",None],
    "Department":["CSE","cse","cse","Data Science","DATA SCIENCE","ECE"],
    "Marks":[85,72,72,np.nan,91,67],
    "Attendance":[90,82,82,75,np.nan,88],
    "Exam_Date":["2026-09-01","01/09/2026","01/09/2026","2026-09-02","not known","2026=09-03"]
})

clean =pd.concat([clean,new_data])

In [ ]:
clean

   Student_Id    Name    Department  Marks  Attendance   Exam_Date
0         101   Rashi           CSE   85.0        90.0  2026-09-01
1         102   Yashi           cse   72.0        82.0  01/09/2026
2         102   Rahul           cse   72.0        82.0  01/09/2026
3         103  Yashi   Data Science    NaN        75.0  2026-09-02
4         104     Yug  DATA SCIENCE   91.0         NaN   not known
5         105    None           ECE   67.0        88.0  2026=09-03
0         101   Rashi           CSE   85.0        90.0  2026-09-01
1         102   Yashi           cse   72.0        82.0  01/09/2026
2         102   Rahul           cse   72.0        82.0  01/09/2026
3         103  Yashi   Data Science    NaN        75.0  2026-09-02
4         104     Yug  DATA SCIENCE   91.0         NaN   not known
5         105    None           ECE   67.0        88.0  2026=09-03

In [ ]:
clean=students.copy()

In [ ]:
print("Exact duplicates:",clean.duplicated().sum())

Exact duplicates: 6

# **Fix inconsistent text**

In [ ]:

unique_students=clean.copy()
unique_students["Name"]=unique_students["Name"].astype("string").str.strip().str.title()

In [ ]:
unique_students

   Student_Id   Name    Department  Marks  Attendance   Exam_Date
0         101  Rashi           CSE   85.0        90.0  2026-09-01
1         102  Yashi           cse   72.0        82.0  01/09/2026
2         102  Rahul           cse   72.0        82.0  01/09/2026
3         103  Yashi  Data Science    NaN        75.0  2026-09-02
4         104    Yug  DATA SCIENCE   91.0         NaN   not known
5         105   <NA>           ECE   67.0        88.0  2026=09-03